version: 2
updates:
  # Update npm packages if they're found weekly.
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  # Update Github Actions if they're found weekly.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
