name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    strategy:
      matrix:
        node-version: [lts/*]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org/'
      - name: Check for lint/formatting errors
        run: |
          npm ci
          npm run lint
  test:
    name: Test
    strategy:
      matrix:
        node-version: [lts/gallium, lts/*, latest]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org/'
      - name: Run library tests
        run: |
          npm ci
          npm test:lib
  publish:
    name: Publish
    needs: [lint, test-library, test-external]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm ci
      - name: Publish package to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build package to upload to GitHub releases
        run: |
          npm pack
          mv rate-limit-redis-*.tgz rate-limit-redis.tgz
      - name: Create a Github release
        uses: softprops/action-gh-release@v1
        with:
          files: rate-limit-redis.tgz
          body:
            You can view the changelog
            [here](https://github.com/express-rate-limit/rate-limit-redis/blob/main/changelog.md).
